FROM node:16-alpine3.12

WORKDIR /code
COPY package*.json ./
RUN npm install --silent
 
COPY . .
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

EXPOSE 3012

CMD ["npm", "run", "dev"]
