global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.17.0.1:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']