apiVersion: 1

datasources:
  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086

  - name: Loki
    type: loki
    access: proxy
    url: http://172.17.0.1:3100

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.17.0.1:9090
    uid: "w9-YqAb4z"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false