FROM nginx:1.21.3-alpine

COPY ./config/nginx.prod.conf /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/prod_sites_enabled
RUN mkdir /etc/nginx/ssl

COPY ./prod_sites_enabled/*.conf /etc/nginx/prod_sites_enabled/
COPY ./ssl/prod/* /etc/nginx/ssl/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]